### ISSUE TITLE
Possible change to notification area

### ISSUE THREAD

**Issue by steverae68** [fastcolors/skin.sio2#43]
Just an idea but pineapple.tv changed the notification area from bottom right of screen to top, so when a notification came it, it dropped down from the top of the screen then scrolled back up when complete.

This is a very ATV experience, any hence we can have something similar ?

**Comment by fastcolors** [comment]
That was definitely in my plans, I need to screenshot the position off my ATV and i'll be on it asap!!

**Comment by fastcolors** [comment]
done. plz check!

**Comment by steverae68** [comment]
I'll check as soon as I get back downstairs

**Comment by steverae68** [comment]
Ok, not quite what I had in mind, if you look at your osd with the draw down bit From the top of the screenn, that's what I mean.

Also, icons on home screen still don't work since that update I mentioned about....

**Comment by fastcolors** [comment]
this is a copy of ATV4 notification, I thought it'd be better to use that since this is a replica of the itv GUI...

to make them work I believe You should reset all skin to default

**Comment by fastcolors** [comment]
![fullsizerender](https://cloud.githubusercontent.com/assets/2766945/21954399/d095802a-da4f-11e6-9cf5-b4a7a588e3ec.jpg)

**Comment by steverae68** [comment]
yeah thats spot on, i never even gave that a thought.......  this can be closed
