### ISSUE TITLE
unable to update to new skin version - dependancy resource.uisounds.sio2 not met

### ISSUE THREAD

**Issue by steverae68** [fastcolors/skin.sio2#46]
As title suggests

i decided to wipe out sio2 completely and start again to see if i can resolve the issue i have with main menu items not working as mentioned earlier.

upon loading latest version of skin i receive the above error meaning no SIO2 skin :(

I've reverted back to build skin.sio2-bd8372ee73418e966b5939e5d359165a0ba879a8
this is the last fully working I've been able to use

**Comment by badrabbit** [comment]
I can confirm this.

**Comment by fastcolors** [comment]
I'm pushing the resource to repository right now..

fingers crossed ;-)

**Comment by fastcolors** [comment]
everything should be in place... could You guys test a fresh install?

**Comment by badrabbit** [comment]
I'm still unable to do a fresh install or update on Kodi Krypton RC3. Dependency error as before.

**Comment by fastcolors** [comment]
still guisounds or more deps?

**Comment by fastcolors** [comment]
did you refresh the repo?

**Comment by badrabbit** [comment]
Right now i'm using the "Download ZIP" option from https://github.com/fastcolors/skin.sio2/tree/ATV4-krypton

Isn't that the correct way?

**Comment by fastcolors** [comment]
nope

add my repo and test from there... then if you want to keep up with developement version you can switch to download zip method.

but I'll be pushing more "normal" updates now that the changes are less.

repo is here:
https://www.dropbox.com/s/az9l5i1r78s1ey8/repository.fastcolors-4.0.1.zip?dl=0

**Comment by badrabbit** [comment]
OK. Thanks!
Install through repo worked went without problems.

But there are 2 bugs i've noticed:
- Can't switch to dark theme anymore (not through skin settings and not from Kodi's interface settings)
- In default skin there's now the dark flash on every window change

**Comment by fastcolors** [comment]
you're right!!

i forgot to add dark.xbt to the skin file!!!
if you now get the zip from GitHub you should solve the issue.

then i'll push the correct update!

**Comment by badrabbit** [comment]
Installed from ZIP - dark mode working correctly again!

Still these bugs are present:
- In default skin there's now the dark flash on every window change
- Some elements on home screen are still not working - LiveTV, Addons, etc.

**Comment by fastcolors** [comment]
try restore skin defaults in skin settings

**Comment by badrabbit** [comment]
Thanks again. Working as expected!

**Comment by fastcolors** [comment]
#48 will update status there
